// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm5luGWxUrMOtTm3FtvsSCHPBvr2zzh7k',
    appId: '1:341364453140:web:c0d832dbbb796696865c01',
    messagingSenderId: '341364453140',
    projectId: 'internship-5d412',
    authDomain: 'internship-5d412.firebaseapp.com',
    storageBucket: 'internship-5d412.firebasestorage.app',
    measurementId: 'G-8EDXHZ1PXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKgQVEBBxD2dikxGtbPORKD7N_Gw-v4G4',
    appId: '1:341364453140:android:6a68bab1e5026f25865c01',
    messagingSenderId: '341364453140',
    projectId: 'internship-5d412',
    storageBucket: 'internship-5d412.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ILMhMYzW8_yx-gUMd_723aMt4h3lPYw',
    appId: '1:341364453140:ios:57602b1b19ec06b2865c01',
    messagingSenderId: '341364453140',
    projectId: 'internship-5d412',
    storageBucket: 'internship-5d412.firebasestorage.app',
    iosBundleId: 'com.example.internship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm5luGWxUrMOtTm3FtvsSCHPBvr2zzh7k',
    appId: '1:341364453140:web:efc1647f7ba2e35a865c01',
    messagingSenderId: '341364453140',
    projectId: 'internship-5d412',
    authDomain: 'internship-5d412.firebaseapp.com',
    storageBucket: 'internship-5d412.firebasestorage.app',
    measurementId: 'G-VEY3WCNVRD',
  );
}
